name: liground-chess # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '0.4.0' # just for humans, typically '1.2+git' or '1.3.2'
summary:  A free, open-source and modern Chess Variant Analysis GUI for the 21st century
description: |
   A free, open-source and modern Chess Variant Analysis GUI for the 21st century

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
icon:  liground_icon.png
title: LiGround Chess

apps:
  liground:
    command: liground
parts:
  liground:
    # See 'snapcraft plugins'
    plugin: dump
    source: .
#    build-packages: [default-jre]
#    stage-packages: [default-jre]
    organize:
      liground: build/
      liground.1: man/man1/

architectures:
  - build-on: amd64

